### ISSUE TITLE
TF Lite Version?

### ISSUE THREAD

**Issue by RoboEvangelist** [juandes/pikachu-detection#1]
Folks,

What is the difference between this and the tensorflow lite version? Is TF Lite faster than plain Android?

**Comment by Djacob502** [comment]
The tf lite version is built specifically for mobile devices and is faster than the mobile version that is used in juandes pikachu detection.  Eventually the plan is for google to replace tflite version for their mobile net but it is a work in progress. Also - at this time tflite for object detection is having some issues.
