### ISSUE TITLE
Hello Juan I'm question your android project

### ISSUE THREAD

**Issue by pdh930105** [juandes/pikachu-detection#2]
Hello. I'm beginner programmer that i'm looking your presentation at PyData through YOUTUBE.
I love Pocketmon too, So Your project is so good and exciting of me.
I want to test your project and run android but don't run your git clone android studio.

How should it be set? Mu System so android studio 3.14 and Galaxy S8+ 8.0.1`

**Comment by juandes** [comment]
Hi @pdh930105 :) glad you enjoyed the presentation. The code here by its own is not enough to build the system. For that, you have to train the model on your own and then used the exported model on the phone. I highly recommend reading the document I wrote describing the whole process: https://towardsdatascience.com/detecting-pikachu-on-android-using-tensorflow-object-detection-15464c7a60cd

**Comment by pdh930105** [comment]
Ok Thanks!

2018년 10월 1일 (월) 오후 10:26, Juan De Dios Santos <notifications@github.com>님이
작성:

**Comment by juandes** [comment]
No problem! Feel free to ask me anything if you need help :)
