### ISSUE TITLE
ISSUE when deployed on app and tested 

### ISSUE THREAD

**Issue by NidhiSultan** [juandes/pikachu-detection#4]
Hi @juandes , I tried the android api from tensorflow site with tflite version model. But not able to get detect any box accurately when trying to test it using the app. Did you face any issue similar to this?
 Though my model is working fine when tested on images using postman.

**Comment by juandes** [comment]
Hi @NidhiSultan. My model is quite outdated and not made for tflite. That's probably why it isn't working. Let me know if you find a fix. Or even better, if you manage to convert it to tflife.

**Comment by NidhiSultan** [comment]
I managed to make it work. Thanks

**Comment by juandes** [comment]
Hi @NidhiSultan , do you mind explaining how? It might help others in the future. Thanks.

**Comment by NidhiSultan** [comment]
Hi @juandes , The model we train and convert to tflite is either Quantized or non quantized. The Android application provided by tensorflow has a parameter, "isQuantized". 
We have 2 options.
1. Quantize our model while converting it to tflite for it to support the application, https://www.tensorflow.org/lite/performance/post_training_quantization.
2. Change the parameter "isQuantized" to False, assuming the android application here is the one take from official tensorflow site mentioned here. https://github.com/tensorflow/models/tree/master/research/object_detection

Thanks Nidhi

**Comment by juandes** [comment]
Hi @NidhiSultan , amazing explanation. I really appreciate the effort. Thanks!
